### ISSUE TITLE
gocd: Custom plugin installation for Elastic Agent in GoCD

### ISSUE THREAD

**Issue by EugenMayer** [disaster37/webcenter-catalog#1]
First, thank you for the template, very nice! I see you stopped publishing into the community-catalog repo as i also did ( .. https://github.com/EugenMayer/docker-rancher-extra-catalogs )

To the GoCD template:
 - do i need to install the elastic agent plugin in addition - not really the swarm plugin ( plugin not yet fully understanding how you setup the rancher integration yet )
 - i am not quiet sure if in understand that right, but since i want my jobs to run in my builders ( builder pattern ) which will need to run the gocd-agent daemon of course, how does this play with your setup?

Thank you

**Comment by EugenMayer** [comment]
Maybe i just wrongy understood you catalog, i guess what you do is just running agents on docker-enging - not really elastic agents in terms they get started / removed as they are in need and also in a type they are in need?

Your catalog has nothing to do with https://www.gocd.org/plugins/#elastic-agents, right?

**Comment by disaster37** [comment]
Hi guy, the gocd elastic plugin dedicated to rancher doesn't not exist actually.

My catalog, permit to launch GoCD server and run X instance of GoCD agent that join automatically the GoCD server. But it's persistant agent (worker).


If you should use my catalog, prefer to use my branch develop (better up to date and fix patch).


________________________________
De : Eugen Mayer <notifications@github.com>
Envoyé : jeudi 9 novembre 2017 08:05
À : disaster37/webcenter-catalog
Cc : Subscribed
Objet : Re: [disaster37/webcenter-catalog] gocd: Custom plugin installation for Elastic Agent in GoCD (#1)


Maybe i just wrongy understood you catalog, i guess what you do is just running agents on docker-enging - not really elastic agents in terms they get started / removed as they are in need and also in a type they are in need?

I guess its about either doing https://www.gocd.org/plugins/#elastic-agents

Supported Plugins | GoCD<https://www.gocd.org/plugins/#elastic-agents>
www.gocd.org
GoCD supported official and community plugins. Add a plugin for Slack notifications, Docker, AWS, and more.

**Comment by EugenMayer** [comment]
seen and understood https://github.com/disaster37/webcenter-catalog/blob/master/templates/gocd/3/docker-compose.yml.tpl#L99 ... so what i do is install the plugin and do deploy 0 agents in rancher, then user elastic agents.

Any chances you update the version to your newes .10.x builds?

**Comment by EugenMayer** [comment]
@disaster37 but you exposed the docker enging, that is all you need for elastic agents?

**Comment by EugenMayer** [comment]
oh now i understand, what you did is expose the docker-engine to the agent, so the agent himself can start docker-containters - but you did not expose the docker-enginge of rancher to the gocd server so it can run elastic agents, right?

**Comment by disaster37** [comment]
I d'ont understand your mistake. I doesn't use elastic-agent anywhere. The docker engine that you can found in docker-compose is just here to use docker in your CD pipline.


I my case, the GoCD agent is generic (not specialized for java, or Golang, etc.), it juste support docker to build your code with docker image that contain your specificity (java, golang, etc.).


I hope to be clear ;)


________________________________
De : Eugen Mayer <notifications@github.com>
Envoyé : jeudi 9 novembre 2017 08:27
À : disaster37/webcenter-catalog
Cc : disaster37; Mention
Objet : Re: [disaster37/webcenter-catalog] gocd: Custom plugin installation for Elastic Agent in GoCD (#1)


oh now i understand, what you did is expose the docker-engine to the agent, so the agent himself can start docker-containters - but you did not expose the docker-enginge of rancher to the gocd server so it can run elastic agents, right?

**Comment by EugenMayer** [comment]
I understand, you might just missed something.

Instead of creating container yourself using tasks manually, copying materials into those and mounting volumes, handling the whole container lifecycle ..

You rather use elastic agents where you can define, in the gocd job, which docker-image to use, thus you can use the builder pattern properly and much more easy
